<?php
//DO NOT EDIT THIS FILE
require("db.php");
require("function.php");
global $table_name;
global $mysqli;
global $param1;
global $param2;
global $param3;
global $param4;
$query = "SELECT * FROM $table_name ORDER BY runtime desc";
$result = mysqli_query($mysqli, $query);
echo "<h1>Script Stats Usage Hiscores</h1><br/>";
if(mysqli_num_rows($result) > 0) {
	echo "<table border='1' cellpadding='10'>";
	echo "<tr><td>username</td><td>run time</td><td>".$param1."</td><td>".$param2."</td><td>".$param3."</td><td>".$param4."</td>";
	for($i=0;$i<mysqli_num_rows($result);$i++) {
		$row = mysqli_fetch_assoc($result);
		echo "<tr>";
		echo "<td>".$row["username"]."</td>";
		echo "<td>".convert_seconds($row["runtime"])."</td>";
		echo "<td>".$row["var1"]."</td>";
		echo "<td>".$row["var2"]."</td>";
		echo "<td>".$row["var3"]."</td>";
		echo "<td>".$row["var4"]."</td>";
		echo "</tr>";
	}
	echo "</table>";
}
else {
	echo "No entries in the hiscores yet.";
}
?>